Repository ansible-middleware/keycloak, pull requests merged in 2023-03, with the labels that each got.

#53 Update keycloak.conf.j2
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: bugfixes

#60 Provide config for multiple modcluster proxies
  molecule/default/converge.yml
  roles/keycloak/README.md
  roles/keycloak/defaults/main.yml
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/main.yml
  roles/keycloak/templates/standalone-infinispan.xml.j2
  roles/keycloak/templates/standalone.xml.j2
  roles/keycloak/vars/main.yml
Labels: major_changes

#61 Drop community.general from dependencies
  galaxy.yml
  plugins/doc_fragments/attributes.py
  plugins/doc_fragments/keycloak.py
  plugins/module_utils/identity/keycloak/keycloak.py
  plugins/modules/keycloak_client.py
  plugins/modules/keycloak_role.py
  plugins/modules/keycloak_user_federation.py
  requirements.yml
  roles/keycloak_realm/tasks/main.yml
  roles/keycloak_realm/tasks/manage_client_roles.yml
Labels: minor_changes

#62 Allow to configure TCPPING for discovery
  roles/keycloak/README.md
  roles/keycloak/defaults/main.yml
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/install.yml
  roles/keycloak/templates/standalone-infinispan.xml.j2
Labels: minor_changes

#64 Switch to middleware_automation.common for rh-sso patching
  plugins/filter/version_sort.py
  plugins/module_utils/version.py
  roles/keycloak/README.md
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/rhsso_patch.yml
Labels: minor_changes
