Repository ansible-middleware/keycloak, pull requests merged in 2023-11, with the labels that each got.

#120 feat: add a destination variable for the log link
  molecule/default/converge.yml
  molecule/default/verify.yml
  molecule/quarkus/converge.yml
  molecule/quarkus/verify.yml
  roles/keycloak/README.md
  roles/keycloak/defaults/main.yml
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/main.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/main.yml
Labels: minor_changes, hacktoberfest-accepted

#122 Update Keycloak to version 22.0.5
  molecule/quarkus/prepare.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
Labels: minor_changes

#124 feat: jboss port offset configuration
  molecule/default/converge.yml
  molecule/default/verify.yml
  roles/keycloak/README.md
  roles/keycloak/defaults/main.yml
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/templates/15.0.8/standalone-infinispan.xml.j2
  roles/keycloak/templates/15.0.8/standalone.xml.j2
  roles/keycloak/templates/9.0.2/standalone-infinispan.xml.j2
  roles/keycloak/templates/9.0.2/standalone.xml.j2
  roles/keycloak/templates/standalone-ha.xml.j2
  roles/keycloak/templates/standalone-infinispan.xml.j2
  roles/keycloak/templates/standalone.xml.j2
  roles/keycloak/vars/main.yml
  roles/keycloak_realm/meta/argument_specs.yml
  roles/keycloak_realm/vars/main.yml
Labels: minor_changes

#116 [keycloak_quarkus] Enable config of a key store and trust store
  molecule/quarkus/converge.yml
  playbooks/keycloak_quarkus.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: breaking_changes

#119 Update minimum ansible-core version > 2.14
  README.md
  galaxy.yml
  meta/runtime.yml
  roles/keycloak/meta/main.yml
  roles/keycloak_quarkus/meta/main.yml
  roles/keycloak_realm/meta/main.yml
Labels: breaking_changes
