Repository ansible-middleware/keycloak, pull requests merged in 2024-02, with the labels that each got.

#159 #158: Feature/inifinispan TCPPING
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/main.yml
  roles/keycloak_quarkus/tasks/rebuild_config.yml
  roles/keycloak_quarkus/templates/cache-ispn.xml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
  roles/keycloak_quarkus/templates/keycloak.service.j2
Labels: major_changes

#161 keycloak_quarkus: Allow configuring log rotate options in quarkus configuration
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/quarkus.properties.j2
Labels: minor_changes

#163 keycloak_quarkus: `sticky-session`s for infinispan routes
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: minor_changes

#167 Set enable-recovery when xa transactions are enabled
  roles/keycloak_quarkus/templates/quarkus.properties.j2
Labels: minor_changes

#171 keycloak_quarkus: fix custom JAVA_HOME parameter name
  molecule/https_revproxy/prepare.yml
  molecule/quarkus-devmode/converge.yml
  molecule/quarkus-devmode/prepare.yml
  molecule/quarkus-devmode/verify.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
Labels: bugfixes
