Repository ansible-middleware/keycloak, pull requests merged in 2024-03, with the labels that each got.

#176 Utilize comment filter for `ansible_managed` annotations
  molecule/overridexml/templates/custom.xml.j2
  roles/keycloak/templates/15.0.8/standalone-infinispan.xml.j2
  roles/keycloak/templates/15.0.8/standalone.xml.j2
  roles/keycloak/templates/keycloak-service.sh.j2
  roles/keycloak/templates/keycloak-sysconfig.j2
  roles/keycloak/templates/keycloak.service.j2
  roles/keycloak/templates/standalone-ha.xml.j2
  roles/keycloak/templates/standalone-infinispan.xml.j2
  roles/keycloak/templates/standalone.xml.j2
  roles/keycloak_quarkus/templates/cache-ispn.xml.j2
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
  roles/keycloak_quarkus/templates/keycloak.conf.j2
  roles/keycloak_quarkus/templates/keycloak.service.j2
  roles/keycloak_quarkus/templates/quarkus.properties.j2
Labels: bugfixes

#180 Use `keycloak_realm` as default for sub-entities
  roles/keycloak_realm/tasks/main.yml
  roles/keycloak_realm/tasks/manage_client_roles.yml
  roles/keycloak_realm/tasks/manage_user_client_roles.yml
Labels: minor_changes

#181 Multi distro refactor
  .github/workflows/ci.yml
  molecule/debian/converge.yml
  molecule/debian/molecule.yml
  molecule/debian/prepare.yml
  molecule/debian/roles
  molecule/debian/verify.yml
  molecule/default/converge.yml
  molecule/requirements.yml
  roles/keycloak/defaults/main.yml
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/main.yml
  roles/keycloak/tasks/prereqs.yml
  roles/keycloak/tasks/systemd.yml
  roles/keycloak/templates/keycloak-sysconfig.j2
  roles/keycloak/templates/keycloak.service.j2
  roles/keycloak/vars/debian.yml
  roles/keycloak/vars/redhat.yml
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/meta/main.yml
  roles/keycloak_quarkus/tasks/debian.yml
  roles/keycloak_quarkus/tasks/fastpackages.yml
  roles/keycloak_quarkus/tasks/main.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/tasks/systemd.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
  roles/keycloak_quarkus/templates/keycloak.service.j2
  roles/keycloak_quarkus/vars/debian.yml
  roles/keycloak_quarkus/vars/redhat.yml
Labels: internal
