Repository ansible-middleware/keycloak, pull requests merged in 2024-04, with the labels that each got.

#184 Fix permissions on controller-side downloaded artifacts
  roles/keycloak_quarkus/tasks/install.yml
Labels: bugfixes

#186 JVM arguments go in JAVA_OPTS
  molecule/default/converge.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
Labels: bugfixes

#187 Permit parse reverse proxy headers
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: minor_changes

#191 Unrelax configuration file permissions
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/jdbc_driver.yml
  roles/keycloak_quarkus/tasks/main.yml
  roles/keycloak_quarkus/tasks/systemd.yml
Labels: bugfixes

#192 Comprehensive linter warning fixes
  galaxy.yml
  molecule/prepare.yml
  molecule/quarkus-devmode/prepare.yml
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/fastpackages.yml
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/jdbc_driver.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/tasks/systemd.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
  roles/keycloak_quarkus/vars/debian.yml
  roles/keycloak_realm/defaults/main.yml
  roles/keycloak_realm/meta/argument_specs.yml
  roles/keycloak_realm/tasks/manage_client_users.yml
  roles/keycloak_realm/tasks/manage_user_client_roles.yml
Labels: internal

#189 #188: add support for configuration key store
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/config_store.yml
  roles/keycloak_quarkus/tasks/deprecations.yml
  roles/keycloak_quarkus/tasks/main.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
  roles/keycloak_quarkus/vars/main.yml
Labels: major_changes

#194 Update keycloak to 24.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
Labels: minor_changes

#196 Keystore based vault SPI
  molecule/quarkus/converge.yml
  molecule/quarkus/prepare.yml
  molecule/quarkus/verify.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: minor_changes

#197 #190: remove `keycloak_quarkus_admin_user[_pass]` once keycloak is bootstrapped
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/tasks/bootstrapped.yml
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/main.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
  roles/keycloak_quarkus/templates/keycloak.fact.j2
  roles/keycloak_quarkus/vars/main.yml
Labels: minor_changes

#195 Added hostname-strict-https option
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: minor_changes

#201 Providers config and custom providers
  molecule/quarkus/converge.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: minor_changes
