Repository ansible-middleware/keycloak, pull requests merged in 2024-05, with the labels that each got.

#202 Customize jdbc driver downloads, optional authentication
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/jdbc_driver.yml
Labels: minor_changes

#204 Fix logic in when clause
  roles/keycloak_quarkus/tasks/jdbc_driver.yml
Labels: bugfixes

#207 jdbc_download and validate_certs params update
  github.json
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/jdbc_driver.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/jdbc_driver.yml
Labels: minor_changes

#209 controller priv escalation
  roles/keycloak_quarkus/tasks/install.yml
Labels: bugfixes

#210 Enable copying of key material
  molecule/quarkus/converge.yml
  molecule/quarkus/prepare.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/install.yml
Labels: minor_changes

#213 Linter warnings fix pass
  .ansible-lint
  changelogs/config.yaml
  roles/keycloak/meta/argument_specs.yml
  roles/keycloak/tasks/fastpackages.yml
  roles/keycloak/tasks/install.yml
  roles/keycloak/tasks/jdbc_driver.yml
  roles/keycloak/tasks/prereqs.yml
  roles/keycloak/tasks/restart_keycloak.yml
  roles/keycloak/tasks/rhsso_cli.yml
  roles/keycloak/tasks/rhsso_patch.yml
  roles/keycloak/tasks/systemd.yml
  roles/keycloak/vars/debian.yml
  roles/keycloak/vars/main.yml
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/jdbc_driver.yml
Labels: internal

#217 Port downstream upgrade
  .github/workflows/ci.yml
  molecule/quarkus_upgrade/converge.yml
  molecule/quarkus_upgrade/molecule.yml
  molecule/quarkus_upgrade/prepare.yml
  molecule/quarkus_upgrade/vars.yml
  molecule/quarkus_upgrade/verify.yml
Labels: internal

#218 Update Keycloak to version 24.0.4
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
Labels: minor_changes

#220 Download from alternate URL with optional http authentication
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/tasks/install.yml
Labels: minor_changes

#229 Allow to add extra custom env vars in sysconfig file
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
Labels: minor_changes

#223 Allow for custom providers hosted on maven repositories
  molecule/quarkus/converge.yml
  requirements.txt
  requirements.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
Labels: major_changes

#231 Restart handler strategy behaviour
  .github/workflows/ci.yml
  .gitignore
  molecule/quarkus/converge.yml
  molecule/quarkus_ha/converge.yml
  molecule/quarkus_ha/molecule.yml
  molecule/quarkus_ha/postgresql/postgresql.conf
  molecule/quarkus_ha/prepare.yml
  molecule/quarkus_ha/roles
  molecule/quarkus_ha/verify.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/handlers/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/install.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/tasks/restart.yml
  roles/keycloak_quarkus/tasks/restart/none.yml
  roles/keycloak_quarkus/tasks/restart/serial.yml
  roles/keycloak_quarkus/tasks/restart/serial_then_parallel.yml
  roles/keycloak_quarkus/templates/quarkus.properties.j2
  roles/keycloak_quarkus/vars/main.yml
Labels: major_changes

#227 `proxy-header` enhancement
  molecule/debian/converge.yml
  molecule/https_revproxy/converge.yml
  molecule/quarkus-devmode/converge.yml
  molecule/quarkus/converge.yml
  molecule/quarkus_ha/converge.yml
  molecule/quarkus_upgrade/converge.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/deprecations.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: minor_changes

#232 Update minimum ansible-core version > 2.15
  .github/workflows/ci.yml
  .yamllint
  README.md
  meta/runtime.yml
  roles/keycloak/meta/main.yml
  roles/keycloak/tasks/fastpackages.yml
  roles/keycloak_quarkus/meta/main.yml
  roles/keycloak_realm/meta/main.yml
Labels: major_changes
