Repository ansible-middleware/keycloak, pull requests merged in 2025-04, with the labels that each got.

#254 Role support for keycloak/RHBK v26
  molecule/debian/converge.yml
  molecule/debian/prepare.yml
  molecule/debian/verify.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/default/verify.yml
  molecule/https_revproxy/converge.yml
  molecule/overridexml/molecule.yml
  molecule/quarkus-devmode/converge.yml
  molecule/quarkus-devmode/molecule.yml
  molecule/quarkus/converge.yml
  molecule/quarkus/molecule.yml
  molecule/quarkus/prepare.yml
  molecule/quarkus/verify.yml
  molecule/quarkus_ha/converge.yml
  molecule/quarkus_ha/molecule.yml
  molecule/quarkus_upgrade/converge.yml
  molecule/quarkus_upgrade/molecule.yml
  molecule/quarkus_upgrade/prepare.yml
  molecule/quarkus_upgrade/vars.yml
  molecule/quarkus_upgrade/verify.yml
  playbooks/keycloak_quarkus.yml
  playbooks/keycloak_quarkus_dev.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/deprecations.yml
  roles/keycloak_quarkus/tasks/firewalld.yml
  roles/keycloak_quarkus/tasks/main.yml
  roles/keycloak_quarkus/tasks/prereqs.yml
  roles/keycloak_quarkus/templates/cache-ispn.xml.j2
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
  roles/keycloak_quarkus/templates/keycloak.conf.j2
  roles/keycloak_quarkus/vars/main.yml
  roles/keycloak_quarkus/vars/redhat.yml
Labels: breaking_changes

#266 Bump major and ansible-core versions
  CONTRIBUTING.md
  README.md
  docs/requirements.txt
  galaxy.yml
  meta/runtime.yml
  molecule/default/molecule.yml
  molecule/https_revproxy/molecule.yml
  molecule/overridexml/molecule.yml
  molecule/quarkus-devmode/molecule.yml
  molecule/quarkus/converge.yml
  molecule/quarkus/molecule.yml
  molecule/quarkus/verify.yml
  molecule/quarkus_ha/molecule.yml
  roles/keycloak/meta/main.yml
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/meta/main.yml
  roles/keycloak_quarkus/tasks/restart.yml
  roles/keycloak_quarkus/tasks/start.yml
  roles/keycloak_realm/meta/main.yml
Labels: breaking_changes

#268 keycloak_realm: change url variables to defaults
  roles/keycloak/defaults/main.yml
  roles/keycloak/vars/main.yml
  roles/keycloak_realm/defaults/main.yml
  roles/keycloak_realm/vars/main.yml
Labels: minor_changes

#269 Update example playbooks to use new `bootstrap` var
  playbooks/keycloak_quarkus.yml
  playbooks/keycloak_quarkus_dev.yml
Labels: documentation

#271 Rename and honour parameter `keycloak_quarkus_http_host`
  roles/keycloak_quarkus/README.md
  roles/keycloak_quarkus/defaults/main.yml
  roles/keycloak_quarkus/meta/argument_specs.yml
  roles/keycloak_quarkus/tasks/deprecations.yml
  roles/keycloak_quarkus/templates/cache-ispn.xml.j2
  roles/keycloak_quarkus/templates/keycloak.conf.j2
Labels: bugfixes

#274 Load environment vars during kc rebuild
  molecule/quarkus/converge.yml
  roles/keycloak_quarkus/tasks/rebuild_config.yml
  roles/keycloak_quarkus/tasks/systemd.yml
  roles/keycloak_quarkus/templates/keycloak-sysconfig.j2
  roles/keycloak_quarkus/vars/debian.yml
  roles/keycloak_quarkus/vars/redhat.yml
Labels: bugfixes
